### ISSUE TITLE
Singular matrix error

### ISSUE THREAD

**Issue by joehudson** [Oleffa/LeagueAI#7] opened 2019-05-07 18:18 UTC
I don't know if you are still working on it but I keep having this error raised. The only thing I modified was the window and monitor resolution to 1920x1080. I've also been running the py file instead of the ipynb, so I don't know if it's a specific problem with the py file itself. Thanks

------------------------------------------
Traceback (most recent call last):
  File "C:/Users/hudso/Desktop/Machine learning/object detection test/models/research/object_detection/LeagueAI-Oleffa/LeagueAI.py", line 655, in <module>
    estimate_policy_gradient_FD()
  File "C:/Users/hudso/Desktop/Machine learning/object detection test/models/research/object_detection/LeagueAI-Oleffa/LeagueAI.py", line 309, in estimate_policy_gradient_FD
    policy_grad = ((inv((delta_theta.reshape((-1,4)).T).dot(delta_theta.reshape((-1,4))))
  File "C:\Users\hudso\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "C:\Users\hudso\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

**Comment by Oleffa** [comment] 2019-05-13 07:48
Hi,

unfortunately I am currently not working anymore on this version. I will see if I can reproduce the error if I have time.

About your error, has it worked with the jupyter notebook? Has it worked with the old resolution? 
I have actually only tested it with the 1366x768 resolution on my notebook back then. 
The images I trained the object detector with had this resolution as well. So the problem could be that you need to reshape the input array from 1920x1080 to 1366x768 when feeding it to the object detection part. Maybe a resolution with the same aspect ratio as 1366x768 works too.
Something like:
`cv2.resize(image_np, (1366, 768))`
If it worked before with the smaller resolution my suggestion would be to run the game in window mode in 1366x768. So you can also see the AI view window.

Sorry if it was not too helpful, but I am currently working on a new version of the LeagueAI which will be more flexible and easy to set up, so I won't invest too much time into fixing the current version.

Best Regards

**Comment by grant0500** [comment] 2019-06-19 09:36
Will there be a new release for this update?

**Comment by Oleffa** [comment] 2019-06-19 09:45
Hi, I recently replaced the version that caused this bug with a new implementation. It will be designed to be more of a framework that allows you to build your own applications. I will be adding more documentation and features gradually during the next weeks. I will close this issue because it is related to an older, unsupported version.

**Closed as completed by Oleffa** 2019-06-19 09:45 UTC
